routes:
  - name: view#index
    url: /
    verb: GET

  - name: view#timezoneIndex
    url: /js/timezones.json
    verb: GET

  - name: view#setView
    url: /setView/{view}
    verb: GET

  - name: export#exportAll
    url: /export/all
    verb: GET

  - name: export#exportAllInTimeRange
    url: /export/all/{from}/{to}
    verb: GET

  - name: export#exportCalendar
    url: /export/calendar/{calendarId}
    verb: GET

  - name: export#exportCalendarInTimeRange
    url: /export/calendar/{calendarId}/{from}/{to}
    verb: GET

  - name: export#exportEvent
    url: /export/event/{calendarId}/{uid}
    verb: GET

  - name: import#importFile
    url: /import/{file}
    verb: GET

  - name: import#importFileInTimeRange
    url: /import/{file}/{from}/{to}
    verb: GET

  - name: import#importRaw
    url: /import/raw
    verb: POST

  - name: import#importRawInTimeRange
    url: /import/raw/{from}/{to}
    verb: POST

resources:
    backend:
        url: /backends
    calendars:
        url: /calendars
    events:
        url: /calendars/{calendarId}/events
    todos:
        url: /calendars/{calendarId}/todos
    journals:
        url: /calendars/{calendarId}/journals